### PR TITLE
Xrc 2089 add nan checks for zero faces

### PR DESCRIPTION
**Pull request by kiran1228**
Fixes the crash that was seen on some sequences from pwc and ntt.

### CODE REVIEW

**Comment by kiran1228** [comment]
~~adding dnm flag until ilia reviews the fbxs~~

**Comment by kiran1228** [comment]
I'm not seeing any regressions from my testing and ilia confirmed the problem sequences are working. Should be good to merge if you guys are good with this.

**Comment by kiran1228** [comment]
@svensht2 @DillonSkeehan you guys happy with this change?

**Comment by DillonSkeehan** [comment]
this fine with me.

**Review by DillonSkeehan — APPROVED** [review]

**Comment by kiran1228** [comment]
merging

**Pull request merged**
